export default {
  common: { save:'Save', cancel:'Cancel', submit:'Submit', search:'Search', back:'Back', confirm:'Confirm', delete:'Delete', edit:'Edit', view:'View', close:'Close', yes:'Yes', no:'No', loading:'Loading...', noData:'No Data', total:'Total', page:'Page', items:'items', all:'All', filter:'Filter', reset:'Reset', add:'Add', remove:'Remove', enable:'Enable', disable:'Disable', upload:'Upload', download:'Download', preview:'Preview', logout:'Logout', profile:'Profile', settings:'Settings', tip:'Tip', success:'Success', fail:'Failed', required:'Required', optional:'Optional', detail:'Detail', list:'List', action:'Action', status:'Status', time:'Time', name:'Name', description:'Description', note:'Note', home:'Home', ok:'OK' },
  nav: { home:'Home', dashboard:'Dashboard', profile:'My Profile', applications:'My Applications', tracking:'Cargo Tracking', wallet:'My Wallet', prices:'Price Query', orders:'My Orders', upload:'Upload Documents', review:'Applications', reviewHistory:'Review History', pendingCharge:'Pending Charges', feeEstimate:'Fee Estimate', adminHome:'Admin Dashboard', allSubmissions:'All Submissions', employees:'Employees', customers:'Customers', priceRules:'Price Rules', sysSettings:'Settings', exportData:'Export for Next', notifications:'Notifications' },
  status: { pendingReview:'Pending Review', approved:'Approved', pendingPayment:'Pending Payment', paid:'Paid', warehouseReceiving:'Warehouse Receiving', inTransit:'In Transit', arrivedThailand:'Arrived at TH Warehouse', inCustoms:'In Customs', released:'Released', outForDelivery:'Out for Delivery', completed:'Completed', rejected:'Rejected', draft:'Draft', registered:'Registered' },
  payment: { pending:'Pending', paid:'Paid', failed:'Charge Failed', pendingRetry:'Pending Top-up', amount:'Amount', balance:'Balance', chargeTime:'Charge Time', autoDeduct:'Auto-deduct when arrived', confirmCharge:'Confirm Charge', totalPayable:'Amount Due', chargeSuccess:'Charged', refunded:'Refunded' },
  order: { orderNo:'Order No.', company:'Company', product:'Product', tariff:'Tariff', freight:'Freight', updatedAt:'Updated', completedAt:'Completed', submittedAt:'Submitted', clientName:'Client', clientEmail:'Email', reviewStatus:'Status', chargeStatus:'Payment' },
  fee: { intlFreight:'Intl Freight', domesticFreight:'Domestic Freight', storageFee:'Storage Fee', addonServices:'Add-ons', totalCost:'Total', byVolume:'By Volume', byWeight:'By Weight', takeHigher:'Charge the higher', route:'Route', volume:'Volume(CBM)', weight:'Weight(KG)', logistics:'Domestic', warehouseDate:'Entry Date', palletCount:'Pallets', woodenBox:'Wooden Box CBM', needFormE:'Form E', calculate:'Calculate', estimate:'Fee Estimate', estimateTitle:'Fee Calculator', estimateDesc:'Standalone tool for quick quotes', autoSaved:'Saved', saving:'Saving...' },
  route: { nanning:'Nanning→Bangkok', guangzhou:'Guangzhou/SZ→Bangkok', yiwu:'Yiwu→Bangkok', nanningShort:'Nanning', guangzhouShort:'Guangzhou/SZ', yiwuShort:'Yiwu' },
  warehouse: { title:'Warehouse Address', shipHere:'Please ship to this address', contact:'Contact', phone:'Phone', name:'Warehouse', address:'Address' },
  product: { info:'Product Info', thaiName:'Thai Name', engName:'English Name', hsCode:'HS Code', tariffRate:'Tariff Rate', formE:'Form E', license:'License', description:'Description', images:'Images', reviewConfirm:'Review Confirmation', available:'Available', unavailable:'N/A', required2:'Required', notRequired:'Not Required' },
  company: { info:'Company Info', name:'Company Name', thaiAddress:'Thai Address', files:'Files', dbd:'DBD', pp20:'PP.20', stamp:'Company Stamp', passport:'Director Passport' },
  customs: { info:'Customs Authorization', type:'Type', director:'Director', agent:'Agent', account:'Account', password:'Password', hasPassport:'Passport Original', provided:'Provided', notConfirmed:'Unconfirmed', agentFiles:'Agent Files', poaFile:'Power of Attorney', pp20Signed:'PP.20 Signed', dbdSigned:'DBD Signed' },
  tax: { info:'Tax Rebate', type2:'Type', needRebate:'Rebate', noRebate:'Freight Forwarder', customsCompany:'Customs Broker', logisticsContact:'Logistics Contact', logisticsCode:'Logistics Code', invoice:'Invoice', packingList:'Packing List' },
  shipment: { info:'Shipment', confirmed:'Confirmed', trackingNo:'Tracking No.', shippedAt:'Shipped At', arrivedAt:'Arrived At', statusConfirmed:'Confirmed', statusPending:'Pending' },
  review: { pending:'Pending', approved2:'Approved', registered:'Registered', rejected:'Rejected', approve:'Approve', reject:'Reject', rejectReason:'Reason', nextAccount:'Next Account', registerStatus:'Status', registerSuccess:'Success', registerFailed:'Failed', registering:'In Progress', saveRegister:'Save', registered2:'Registered', timeline:'Timeline', noRecord:'No records' },
  button: { viewDetail:'View', advance:'Advance to', approve2:'Approve', reject2:'Reject', calculate2:'Calculate', recharge:'Top Up', deposit:'Deposit', exportNext:'Export for Next', confirmCharge2:'Confirm Charge', markArrived:'Mark Arrived & Charge', checkBalance:'Check Balance', balanceSufficient:'Sufficient', balanceInsufficient:'Insufficient' },
  client: {
    dashboard: { welcome:'Welcome back', roleLabel:'Logged in as', allApps:'All', pendingReview2:'Reviewing', approved2:'Approved', rejected2:'Rejected' },
    upload: { title:'Upload Documents', stepLabel:'Step X/Y', step1:'Product', step1Desc:'Confirm import info', step2:'Company', step2Desc:'Upload company docs', step3:'Customs', step3Desc:'Customs registration', step4:'Tax', step4Desc:'Tax rebate info', prev:'Previous', next:'Next', saveDraft:'Save Draft', submitData:'Submit', submitConfirm:'Submit for review?', submitOk:'Confirm', submitCancel:'Review Again', submitSuccess:'Submitted successfully!' },
    submissions: { title:'My Applications', filterAll:'All', filterPending:'Reviewing', filterApproved:'Approved', filterRegistered:'Registered', filterRejected:'Rejected', empty:'No applications', goUpload:'Submit New', detailTitle:'Detail', resubmit:'Resubmit' },
    tracking: { title:'Cargo Tracking', empty:'No tracking records' },
    orders: { title:'My Orders', desc:'Completed orders', empty:'No completed orders' },
    wallet: { title:'My Wallet', balance:'Balance', deposit2:'Top Up', amount2:'Amount', history:'History' },
    prices: { title:'Price Query', tabPrices:'Price List', tabEstimate:'Estimate', transport:'Shipping (THB)', addonTitle:'Add-on Services', estimateDesc2:'Enter volume, weight and route to calculate', freightResult:'Est. Freight', footnote:'Prices subject to change. Estimate for reference only.' },
    notifications: { title:'Notifications' },
    orderDetail: { title:'Order Detail' },
    trackingDetail: { title:'Order Overview' }
  },
  employee: {
    dashboard: { title:'Dashboard', pendingReview2:'Pending', toRegister:'To Register' },
    review: { title:'Applications', filterAll:'All', filterPending2:'Reviewing', filterApproved:'Approved', filterRegistered:'Registered', filterRejected2:'Rejected', empty:'None', goDetail:'View', goReview:'Review', registerEntry:'Register', statusTag:'Status', productTag:'Product' },
    reviewDetail: { title:'Review Detail', back:'Back', tabProduct:'Product', tabCompany:'Company', tabCustoms:'Customs', tabTax:'Tax', tabShipment:'Shipment', tabFinance:'Fees', feeParams:'Parameters', intlRoute:'Intl Route', domesticLogistics:'Domestic', transportTitle:'Intl Freight (higher of volume vs weight)', domesticTitle:'Domestic Freight', storageTitle:'Storage Fee', addonTitle2:'Add-ons (check to apply)', addonTotal2:'Add-on Total', summaryTitle:'Summary', totalReceivable:'Total Due', clientBalance:'Balance', charged:'Charged', refunded2:'Refunded', pendingCharge2:'Pending', trackStatus:'Order Status', currentStatus:'Current', nextStatus:'Next', advanceTo:'Advance to', completedAll:'All completed', arrivedWarning:'Advancing will auto-charge from client balance. Confirm fees are set and balance is sufficient.' },
    tracking2: { title:'Cargo Tracking', empty:'No records', filterStatus:'Filter by status' },
    pendingCharge: { title:'Pending Charges', desc:'Orders that failed auto-charge. Confirm manually after client tops up.', empty:'None', confirmButton:'Confirm Charge', confirmMsg:'Charge' },
    feeEstimate: { title:'Fee Estimate', desc:'Standalone calculator for quick quotes', params:'Parameters', result:'Result (THB)', intlFreight2:'Intl Freight', domesticFreight2:'Domestic', storageFee2:'Storage', addonTotal2:'Add-ons', quickNote:'Quick Note', notePlaceholder:'Client name / note (not saved)' },
    export: { title:'Export Summary', back:'Back', basicInfo:'Basic Info', section1:'1. Product', section2:'2. Company', section3:'3. Customs', section4:'4. Tax', section5:'5. Shipment', section6:'6. Fees', section7:'7. Next Info', allFiles:'All Files', notUploaded:'Not uploaded', fileDownload:'Download', feeDetail2:'Intl Freight', domesticFreight3:'Domestic', storageFee3:'Storage', addonServices3:'Add-ons', chargeStatus2:'Status', selected:'Yes', notSelected:'No', totalFee:'Total' }
  },
  admin: {
    dashboard: { title:'Admin Dashboard', overview:'Overview', totalClients:'Total Clients', newClientsMonth:'New This Month', ordersMonth:'Orders This Month', revenueMonth:'Revenue This Month', orderDist:'Order Distribution', routeDist:'Route Distribution', financeOverview:'Finance (This Month)', depositTotal:'Deposits', chargeTotal:'Charges', totalBalance2:'Total Balance', recentOrders:'Recent Orders' },
    submissions: { title:'All Submissions', empty:'None' },
    tracking: { title:'Cargo Tracking', empty:'No records' },
    priceRules: { title:'Price Rules', addService:'Add Service', feeName:'Name', unitPrice:'Price (THB)', unit:'Unit', route2:'Route', isActive:'Active', addDialog:'Add Rule', serviceName:'Name', code:'Code', description2:'Description', addSuccess:'Added', delConfirm:'Delete? Cannot be undone.', delSuccess:'Deleted', updateSuccess:'Updated', unitFixed:'Per Order', unitCbm:'Per m³', unitKg:'Per kg', unitPallet:'Per Pallet', routeGeneric:'General' },
    employees: { title:'Employees', create:'Create', username:'Username', email:'Email', role:'Role', status2:'Status', createdAt:'Created', generatedPwd:'Password', noData:'No employees' },
    customers: { title:'Customers', submissions2:'Applications', transactions:'Transactions' },
    settings: { title:'Settings' }
  },
  login: { title:'ZhengQing System', subtitle:'Logistics Customs Clearance Platform', username2:'Username', password2:'Password', loginBtn:'Login', rememberMe:'Remember', forgotPassword:'Forgot Password', loginFailed:'Login Failed' },
  error: { forbidden:'Forbidden', forbiddenDesc:'You do not have permission', notFound:'Not Found', notFoundDesc:'Page not found', backHome:'Back to Home' }
}
