export default {
  common: { save:'บันทึก', cancel:'ยกเลิก', submit:'ส่ง', search:'ค้นหา', back:'กลับ', confirm:'ยืนยัน', delete:'ลบ', edit:'แก้ไข', view:'ดู', close:'ปิด', yes:'ใช่', no:'ไม่', loading:'กำลังโหลด...', noData:'ไม่มีข้อมูล', total:'ทั้งหมด', page:'หน้า', items:'รายการ', all:'ทั้งหมด', filter:'กรอง', reset:'รีเซ็ต', add:'เพิ่ม', remove:'ลบ', enable:'เปิด', disable:'ปิด', upload:'อัปโหลด', download:'ดาวน์โหลด', preview:'ดูตัวอย่าง', logout:'ออกจากระบบ', profile:'ข้อมูลส่วนตัว', settings:'ตั้งค่า', tip:'คำแนะนำ', success:'สำเร็จ', fail:'ล้มเหลว', required:'จำเป็น', optional:'ไม่บังคับ', detail:'รายละเอียด', list:'รายการ', action:'ดำเนินการ', status:'สถานะ', time:'เวลา', name:'ชื่อ', description:'คำอธิบาย', note:'หมายเหตุ', home:'หน้าแรก', ok:'ตกลง' },
  nav: { home:'หน้าแรก', dashboard:'แดชบอร์ด', profile:'ข้อมูลของฉัน', applications:'คำขอของฉัน', tracking:'ติดตามสินค้า', wallet:'กระเป๋าเงิน', prices:'สอบถามราคา', orders:'คำสั่งซื้อ', upload:'อัปโหลดเอกสาร', review:'คำขอลูกค้า', reviewHistory:'ประวัติการตรวจสอบ', pendingCharge:'รอยืนยันหักเงิน', feeEstimate:'ประมาณการ', adminHome:'ผู้ดูแลระบบ', allSubmissions:'คำขอทั้งหมด', employees:'พนักงาน', customers:'ลูกค้า', priceRules:'กฎราคา', sysSettings:'ตั้งค่าระบบ', exportData:'ส่งออกสำหรับ Next', notifications:'การแจ้งเตือน' },
  status: { pendingReview:'รอตรวจสอบ', approved:'อนุมัติแล้ว', pendingPayment:'รอชำระเงิน', paid:'ชำระแล้ว', warehouseReceiving:'รับสินค้าที่คลัง', inTransit:'ระหว่างขนส่ง', arrivedThailand:'ถึงคลังไทย', inCustoms:'กำลังตรวจปล่อย', released:'ตรวจปล่อยแล้ว', outForDelivery:'กำลังจัดส่ง', completed:'เสร็จสิ้น', rejected:'ถูกปฏิเสธ', draft:'ฉบับร่าง', registered:'ลงทะเบียนแล้ว' },
  payment: { pending:'รอชำระ', paid:'ชำระแล้ว', failed:'หักเงินล้มเหลว', pendingRetry:'รอเติมเงิน', amount:'จำนวน', balance:'ยอดคงเหลือ', chargeTime:'เวลาหักเงิน', autoDeduct:'หักอัตโนมัติเมื่อถึงคลัง', confirmCharge:'ยืนยันหักเงิน', totalPayable:'ยอดที่ต้องชำระ', chargeSuccess:'หักเงินสำเร็จ', refunded:'คืนเงินแล้ว' },
  order: { orderNo:'เลขที่คำขอ', company:'บริษัท', product:'สินค้า', tariff:'ภาษี', freight:'ค่าขนส่ง', updatedAt:'อัปเดต', completedAt:'เสร็จสิ้น', submittedAt:'ส่งเมื่อ', clientName:'ลูกค้า', clientEmail:'อีเมล', reviewStatus:'สถานะ', chargeStatus:'การชำระเงิน' },
  fee: { intlFreight:'ค่าขนส่งระหว่างประเทศ', domesticFreight:'ค่าขนส่งในประเทศ', storageFee:'ค่าจัดเก็บ', addonServices:'บริการเสริม', totalCost:'รวม', byVolume:'ตามปริมาตร', byWeight:'ตามน้ำหนัก', takeHigher:'คิดตามค่าที่สูงกว่า', route:'เส้นทาง', volume:'ปริมาตร(CBM)', weight:'น้ำหนัก(KG)', logistics:'ขนส่งในประเทศ', warehouseDate:'วันที่เข้าคลัง', palletCount:'จำนวนพาเลท', woodenBox:'กล่องไม้ CBM', needFormE:'ฟอร์ม E', calculate:'คำนวณ', estimate:'ประมาณการ', estimateTitle:'เครื่องคิดค่าขนส่ง', estimateDesc:'เครื่องมืออิสระสำหรับคำนวณราคา', autoSaved:'บันทึกแล้ว', saving:'กำลังบันทึก...' },
  route: { nanning:'หนานหนิง→กรุงเทพ', guangzhou:'กวางโจว/เซินเจิ้น→กรุงเทพ', yiwu:'อี้อู→กรุงเทพ', nanningShort:'หนานหนิง', guangzhouShort:'กวางโจว/เซินเจิ้น', yiwuShort:'อี้อู' },
  warehouse: { title:'ที่อยู่คลังสินค้า', shipHere:'กรุณาจัดส่งไปยังที่อยู่นี้', contact:'ผู้ติดต่อ', phone:'โทรศัพท์', name:'คลังสินค้า', address:'ที่อยู่' },
  product: { info:'ข้อมูลสินค้า', thaiName:'ชื่อไทย', engName:'ชื่ออังกฤษ', hsCode:'รหัส HS', tariffRate:'อัตราภาษี', formE:'ฟอร์ม E', license:'ใบอนุญาต', description:'คำอธิบาย', images:'รูปภาพ', reviewConfirm:'การยืนยันของพนักงาน', available:'ใช้ได้', unavailable:'ใช้ไม่ได้', required2:'จำเป็น', notRequired:'ไม่จำเป็น' },
  company: { info:'ข้อมูลบริษัท', name:'ชื่อบริษัท', thaiAddress:'ที่อยู่ในไทย', files:'ไฟล์', dbd:'ไฟล์ DBD', pp20:'ไฟล์ PP.20', stamp:'ตราประทับ', passport:'พาสปอร์ตกรรมการ' },
  customs: { info:'การอนุญาตศุลกากร', type:'ประเภท', director:'กรรมการดำเนินการเอง', agent:'มอบอำนาจ', account:'บัญชี', password:'รหัสผ่าน', hasPassport:'พาสปอร์ตตัวจริง', provided:'มี', notConfirmed:'ยังไม่ยืนยัน', agentFiles:'ไฟล์มอบอำนาจ', poaFile:'หนังสือมอบอำนาจ', pp20Signed:'PP.20 เซ็นแล้ว', dbdSigned:'DBD เซ็นแล้ว' },
  tax: { info:'ข้อมูลคืนภาษี', type2:'ประเภท', needRebate:'ขอคืนภาษี', noRebate:'ตัวแทน freight', customsCompany:'บริษัทศุลกากร', logisticsContact:'ผู้ติดต่อโลจิสติกส์', logisticsCode:'รหัสโลจิสติกส์', invoice:'ใบกำกับสินค้า', packingList:'รายการบรรจุ' },
  shipment: { info:'ข้อมูลการจัดส่ง', confirmed:'ยืนยันแล้ว', trackingNo:'เลขที่ติดตาม', shippedAt:'วันที่จัดส่ง', arrivedAt:'วันที่ถึงคลัง', statusConfirmed:'ยืนยันแล้ว', statusPending:'รอยืนยัน' },
  review: { pending:'รอตรวจ', approved2:'อนุมัติ', registered:'ลงทะเบียน', rejected:'ปฏิเสธ', approve:'อนุมัติ', reject:'ปฏิเสธ', rejectReason:'เหตุผล', nextAccount:'บัญชี Next', registerStatus:'สถานะ', registerSuccess:'สำเร็จ', registerFailed:'ล้มเหลว', registering:'กำลังดำเนินการ', saveRegister:'บันทึก', registered2:'ลงทะเบียน', timeline:'ไทม์ไลน์', noRecord:'ไม่มีบันทึก' },
  button: { viewDetail:'ดู', advance:'เลื่อนเป็น', approve2:'อนุมัติ', reject2:'ปฏิเสธ', calculate2:'คำนวณ', recharge:'เติมเงิน', deposit:'ฝากเงิน', exportNext:'ส่งออก Next', confirmCharge2:'ยืนยันหักเงิน', markArrived:'ยืนยันถึงคลังและหักเงิน', checkBalance:'ตรวจยอด', balanceSufficient:'เพียงพอ', balanceInsufficient:'ไม่เพียงพอ' },
  client: {
    dashboard: { welcome:'ยินดีต้อนรับกลับ', roleLabel:'คุณเข้าสู่ระบบในฐานะ', allApps:'ทั้งหมด', pendingReview2:'กำลังตรวจ', approved2:'อนุมัติ', rejected2:'ปฏิเสธ' },
    upload: { title:'อัปโหลดเอกสาร', stepLabel:'ขั้นตอนที่ X/Y', step1:'สินค้า', step1Desc:'ยืนยันข้อมูลนำเข้า', step2:'บริษัท', step2Desc:'อัปโหลดเอกสารบริษัท', step3:'ศุลกากร', step3Desc:'ลงทะเบียนศุลกากร', step4:'ภาษี', step4Desc:'ข้อมูลคืนภาษี', prev:'ก่อนหน้า', next:'ถัดไป', saveDraft:'บันทึกฉบับร่าง', submitData:'ส่ง', submitConfirm:'ยืนยันการส่งเพื่อตรวจสอบ?', submitOk:'ยืนยัน', submitCancel:'ตรวจสอบอีกครั้ง', submitSuccess:'ส่งสำเร็จแล้ว!' },
    submissions: { title:'คำขอของฉัน', filterAll:'ทั้งหมด', filterPending:'กำลังตรวจ', filterApproved:'อนุมัติ', filterRegistered:'ลงทะเบียน', filterRejected:'ปฏิเสธ', empty:'ไม่มีคำขอ', goUpload:'ส่งคำขอใหม่', detailTitle:'รายละเอียด', resubmit:'ส่งใหม่' },
    tracking: { title:'ติดตามสินค้า', empty:'ไม่มีรายการติดตาม' },
    orders: { title:'คำสั่งซื้อของฉัน', desc:'คำสั่งซื้อที่เสร็จสิ้นแล้ว', empty:'ไม่มีคำสั่งซื้อ' },
    wallet: { title:'กระเป๋าเงิน', balance:'ยอดคงเหลือ', deposit2:'เติมเงิน', amount2:'จำนวน', history:'ประวัติ' },
    prices: { title:'สอบถามราคา', tabPrices:'รายการราคา', tabEstimate:'ประมาณการ', transport:'ค่าขนส่ง (บาท)', addonTitle:'บริการเสริม', estimateDesc2:'กรอกปริมาตร น้ำหนัก และเลือกเส้นทาง', freightResult:'ค่าขนส่งโดยประมาณ', footnote:'ราคาอาจเปลี่ยนแปลงได้ ประมาณการเพื่อการอ้างอิงเท่านั้น' },
    notifications: { title:'การแจ้งเตือน' },
    orderDetail: { title:'รายละเอียดคำสั่งซื้อ' },
    trackingDetail: { title:'ภาพรวมคำสั่งซื้อ' }
  },
  employee: {
    dashboard: { title:'แดชบอร์ด', pendingReview2:'รอตรวจ', toRegister:'รอลงทะเบียน' },
    review: { title:'คำขอลูกค้า', filterAll:'ทั้งหมด', filterPending2:'กำลังตรวจ', filterApproved:'อนุมัติ', filterRegistered:'ลงทะเบียน', filterRejected2:'ปฏิเสธ', empty:'ไม่มี', goDetail:'ดู', goReview:'ตรวจสอบ', registerEntry:'ลงทะเบียน', statusTag:'สถานะ', productTag:'สินค้า' },
    reviewDetail: { title:'รายละเอียด', back:'กลับ', tabProduct:'สินค้า', tabCompany:'บริษัท', tabCustoms:'ศุลกากร', tabTax:'ภาษี', tabShipment:'จัดส่ง', tabFinance:'ค่าธรรมเนียม', feeParams:'พารามิเตอร์', intlRoute:'เส้นทางระหว่างประเทศ', domesticLogistics:'ขนส่งในประเทศ', transportTitle:'ค่าขนส่งระหว่างประเทศ', domesticTitle:'ค่าขนส่งในประเทศ', storageTitle:'ค่าจัดเก็บ', addonTitle2:'บริการเสริม', addonTotal2:'รวมบริการเสริม', summaryTitle:'สรุป', totalReceivable:'ยอดรวม', clientBalance:'ยอดลูกค้า', charged:'หักแล้ว', refunded2:'คืนแล้ว', pendingCharge2:'รอ', trackStatus:'สถานะคำสั่งซื้อ', currentStatus:'ปัจจุบัน', nextStatus:'ถัดไป', advanceTo:'เลื่อนเป็น', completedAll:'เสร็จทั้งหมด', arrivedWarning:'จะหักเงินจากยอดลูกค้าอัตโนมัติ กรุณายืนยันค่าธรรมเนียม' },
    tracking2: { title:'ติดตามสินค้า', empty:'ไม่มี', filterStatus:'กรองตามสถานะ' },
    pendingCharge: { title:'รอยืนยัน', desc:'คำสั่งที่หักเงินล้มเหลว รอยืนยันหลังจากลูกค้าเติมเงิน', empty:'ไม่มี', confirmButton:'ยืนยันหักเงิน', confirmMsg:'หักเงิน' },
    feeEstimate: { title:'ประมาณการ', desc:'เครื่องคิดค่าขนส่งอิสระ', params:'พารามิเตอร์', result:'ผลลัพธ์ (บาท)', intlFreight2:'ระหว่างประเทศ', domesticFreight2:'ในประเทศ', storageFee2:'จัดเก็บ', addonTotal2:'บริการเสริม', quickNote:'หมายเหตุด่วน', notePlaceholder:'ชื่อลูกค้า / หมายเหตุ' },
    export: { title:'สรุปส่งออก', back:'กลับ', basicInfo:'ข้อมูลพื้นฐาน', section1:'1. สินค้า', section2:'2. บริษัท', section3:'3. ศุลกากร', section4:'4. ภาษี', section5:'5. จัดส่ง', section6:'6. ค่าธรรมเนียม', section7:'7. ข้อมูล Next', allFiles:'ไฟล์ทั้งหมด', notUploaded:'ยังไม่ได้อัปโหลด', fileDownload:'ดาวน์โหลด', feeDetail2:'ระหว่างประเทศ', domesticFreight3:'ในประเทศ', storageFee3:'จัดเก็บ', addonServices3:'บริการเสริม', chargeStatus2:'สถานะ', selected:'เลือก', notSelected:'ไม่เลือก', totalFee:'รวม' }
  },
  admin: {
    dashboard: { title:'แดชบอร์ด', overview:'ภาพรวม', totalClients:'ลูกค้าทั้งหมด', newClientsMonth:'ใหม่เดือนนี้', ordersMonth:'คำสั่งเดือนนี้', revenueMonth:'รายได้เดือนนี้', orderDist:'การกระจายคำสั่ง', routeDist:'การกระจายเส้นทาง', financeOverview:'การเงิน (เดือนนี้)', depositTotal:'ฝาก', chargeTotal:'หัก', totalBalance2:'ยอดรวม', recentOrders:'คำสั่งล่าสุด' },
    submissions: { title:'คำขอทั้งหมด', empty:'ไม่มี' },
    tracking: { title:'ติดตามสินค้า', empty:'ไม่มี' },
    priceRules: { title:'กฎราคา', addService:'เพิ่มบริการ', feeName:'ชื่อ', unitPrice:'ราคา (บาท)', unit:'หน่วย', route2:'เส้นทาง', isActive:'ใช้งาน', addDialog:'เพิ่มกฎ', serviceName:'ชื่อ', code:'รหัส', description2:'คำอธิบาย', addSuccess:'เพิ่มแล้ว', delConfirm:'ลบ? ไม่สามารถกู้คืนได้', delSuccess:'ลบแล้ว', updateSuccess:'อัปเดตแล้ว', unitFixed:'ต่อคำสั่ง', unitCbm:'ต่อ ลบ.ม.', unitKg:'ต่อ กก.', unitPallet:'ต่อพาเลท', routeGeneric:'ทั่วไป' },
    employees: { title:'พนักงาน', create:'สร้าง', username:'ชื่อผู้ใช้', email:'อีเมล', role:'บทบาท', status2:'สถานะ', createdAt:'สร้างเมื่อ', generatedPwd:'รหัสผ่าน', noData:'ไม่มี' },
    customers: { title:'ลูกค้า', submissions2:'คำขอ', transactions:'ธุรกรรม' },
    settings: { title:'ตั้งค่า' }
  },
  login: { title:'ระบบเจิ้งชิง', subtitle:'แพลตฟอร์มโลจิสติกส์พิธีการศุลกากร', username2:'ชื่อผู้ใช้', password2:'รหัสผ่าน', loginBtn:'เข้าสู่ระบบ', rememberMe:'จดจำ', forgotPassword:'ลืมรหัสผ่าน', loginFailed:'เข้าสู่ระบบล้มเหลว' },
  error: { forbidden:'ไม่มีสิทธิ์', forbiddenDesc:'ขออภัย คุณไม่มีสิทธิ์เข้าถึง', notFound:'ไม่พบหน้า', notFoundDesc:'ขออภัย ไม่พบหน้าที่คุณต้องการ', backHome:'กลับหน้าแรก' }
}
